from models import Base, Recipe, Ingredient, Cuisine, User, Difficulty
from flask import Flask, jsonify, request
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import relationship, sessionmaker
from sqlalchemy import create_engine
import sys
import codecs

engine=create_engine('postgresql+psycopg2://catalog:password@/catalog')

Session = sessionmaker(bind=engine)
session = Session()
testUser = User(name='Testy Testerson', email='test@test.test', picture='http://www.test.test')
session.add(testUser)
pizza = Cuisine(cuisine_id="Pizza")
chinese = Cuisine(cuisine_id="Chinese")
mexican = Cuisine(cuisine_id="Mexican")
sushi = Cuisine(cuisine_id="Sushi")
indian = Cuisine(cuisine_id="Indian")
italian = Cuisine(cuisine_id="Italian")
easy = Difficulty(difficulty_id="Easy")
intermediate = Difficulty(difficulty_id="Intermediate")
advanced = Difficulty(difficulty_id="Advanced")
session.add_all([pizza, chinese, mexican, sushi, indian, italian, easy, intermediate, advanced])
session.commit()
pizzaRecipe = Recipe(name="pizza pie", description="it's molto bene! Just throw sauce and cheese on dough, heat it up and enjoy!", difficulty="Easy", cuisine_id=pizza.cuisine_id, user_id=testUser.id)
chineseRecipe = Recipe(name="fried rice", description=" Put the mushrooms in a small bowl and cover with boiling water and soak until re-hydrated, about 20 minutes. Drain, squeeze dry, and cut mushrooms in quarters. Set aside.  Heat 1 tablespoon of the peanut oil in a well-seasoned wok or large non-stick skillet over medium-high heat. Swirl to coat the pan. Pour in the eggs, swirl the pan so the egg forms a large thin pancake. (Lift the edge of the egg to allow any uncooked egg to run to the center.) As soon as the egg has set, turn it out of the pan onto a cutting board. Cool, cut into 1 inch pieces.  Wipe out the pan with a paper towel and heat the remaining peanut oil over high heat. Add the scallions and carrots and stir-fry for 1 1/2 minutes. Add the mushrooms, garlic, chile, and ginger, stir-fry for 1 minute more. Add the soy sauce, sesame oil and rice and stir-fry for 2 to 3 minutes. Add the meat, peas, and reserved egg, cook, stirring until heated through, about 2 to 3 minutes. Serve immediately.  Copyright 2001 Television Food Network, G.P. All rights reserved.  ", difficulty="Intermediate", cuisine_id=chinese.cuisine_id, user_id=testUser.id)
mexicanRecipe = Recipe(name="Cheese Quesadilla", description=" Lay the tortillas flat on a cookie sheet. Sprinkle some of the cheese on 1 half of each tortilla. Try not to get it too close to the edge. Fold the tortillas in half over the cheese to make a half-moon. Warm a skillet over low heat and add 1 tablespoon of the butter. Add the tortilla to the skillet and cook until it is lightly brown, about 2 minutes. Using a spatula, gently lift the edge so you can check. When 1 side is brown, turn the tortilla over and cook the other side until brown and the cheese is all gooey. Use a spatula to transfer to individual plates or a large platter. Repeat with remaining butter and tortillas. Top them with the sour cream, salsa and guacamole.  Cook's Note: Ask your adult helper to help you to put the skillet on the cook top and turn the heat to medium.  ", difficulty="Intermediate", cuisine_id=mexican.cuisine_id, user_id=testUser.id)
sushiRecipe = Recipe(name="Shrimp Tempura", description=" Heat oil in a deep-fryer to 375 degrees F (190 degrees C).  Whisk flour, cornstarch, and salt in a large bowl. Make a depression in the center of the flour. Stir in the water and egg yolk. Mix just until moistened; batter will be lumpy. Stir in egg whites.  One at a time, dip shrimp into the batter to coat. Do not batter tails. Carefully place a few shrimp at a time into the hot oil. Fry until golden brown, about 1 1/2 minutes. Drain on paper towels.  ", difficulty="Advanced", cuisine_id=sushi.cuisine_id, user_id = testUser.id)
indianRecipe = Recipe(name="papadum", description="Mix flour, pepper, cumin and salt.  Add water and knead the dough until it is smooth. You may have to add some water, depending on the flour.  Split the dough into 10 or 15 balls.  Roll out one ball at a time to a very thin round layer on a slightly oiled surface.  Dry the papadums in the oven for an hour (at about 100C or 200F).  Right now you can keep them in an airtight container.  Fry the papadums in oil until they are crispy (not too brown!).", difficulty="Advanced", cuisine_id=indian.cuisine_id, user_id=testUser.id)
italianRecipe = Recipe(name = "spaghetti", description ="This is a recipe for spaghetti with sauce.  It's not a great recipe but it will do the trick if you're hungry and just have spaghetti and sauce.  Boil some water, throw in the s'ghetti, cook until at desired toothsomeness, drain in a collander.  Heat sauce on, appropriately, saucepan.  dump sauce on pasta. Sprinkle with parmesan.  Eat.", difficulty="Advanced", cuisine_id=italian.cuisine_id, user_id=testUser.id)
session.add(pizzaRecipe)
session.add(mexicanRecipe)
session.add(chineseRecipe)
session.add(sushiRecipe)
session.add(indianRecipe)
session.add(italianRecipe)
session.commit()
ingredient1 = Ingredient(name="Pasta Sauce", recipe_id=pizzaRecipe.id, amount=1, user_id=testUser.id,unit="cup")
ingredient2 = Ingredient(name="Cheese", recipe_id=pizzaRecipe.id, amount=1, user_id=testUser.id,unit="pound")
ingredient3 = Ingredient(name="Bread dough", recipe_id=pizzaRecipe.id, amount=1, user_id=testUser.id,unit="blob")
ingredient4 = Ingredient(name="Shiitake mushrooms", recipe_id=chineseRecipe.id, amount=8, user_id=testUser.id,unit="dried")
ingredient5 = Ingredient(name="Peanut oil", recipe_id=chineseRecipe.id, amount=3, user_id=testUser.id,unit="tbsp")
ingredient6 = Ingredient(name="Eggs", recipe_id=chineseRecipe.id, amount=2, user_id=testUser.id,unit="large")
ingredient7 = Ingredient(name="Scallions", recipe_id=chineseRecipe.id, amount=4, user_id=testUser.id,unit="thinly sliced")
ingredient8 = Ingredient(name="Carrot", recipe_id=chineseRecipe.id, amount=0.25, user_id=testUser.id,unit="cup minced")
ingredient9 = Ingredient(name="Garlic", recipe_id=chineseRecipe.id, amount=1, user_id=testUser.id,unit="large clove")
ingredient10 = Ingredient(name="Red Chili Flakes", recipe_id=chineseRecipe.id, amount=1, user_id=testUser.id,unit="pinch")
ingredient11 = Ingredient(name="ginger", recipe_id=chineseRecipe.id, amount=1, user_id=testUser.id,unit="teaspoon peeled")
ingredient12 = Ingredient(name="soy sauce", recipe_id=chineseRecipe.id, amount=2, user_id=testUser.id,unit="tablespoons")
ingredient13 = Ingredient(name="Sesame Oil", recipe_id=chineseRecipe.id, amount=1, user_id=testUser.id,unit="teaspoon toasted")
ingredient14 = Ingredient(name="long grain rice", recipe_id=chineseRecipe.id, amount=3, user_id=testUser.id,unit="cups")
ingredient15 = Ingredient(name="cooked ham", recipe_id=chineseRecipe.id, amount=1, user_id=testUser.id,unit="cup")
ingredient16 = Ingredient(name="flour tortillas", recipe_id=mexicanRecipe.id, amount=4, user_id=testUser.id,unit="10 inch")
ingredient17 = Ingredient(name="Cheddar Cheese", recipe_id=mexicanRecipe.id, amount=1, user_id=testUser.id,unit="cup grated")
ingredient18 = Ingredient(name="Butter", recipe_id=mexicanRecipe.id, amount=4, user_id=testUser.id,unit="tbsp")
ingredient19 = Ingredient(name="Sour Cream", recipe_id=mexicanRecipe.id, amount=1, user_id=testUser.id,unit="blob for garnish")
ingredient20 = Ingredient(name="Salsa", recipe_id=mexicanRecipe.id, amount=1, user_id=testUser.id,unit="blob for garnish")
ingredient21 = Ingredient(name="All purpose flour", recipe_id=sushiRecipe.id, amount=1, user_id=testUser.id,unit="cup")
ingredient22 = Ingredient(name="cornstarch", recipe_id=sushiRecipe.id, amount=2, user_id=testUser.id,unit="tbsp")
ingredient23 = Ingredient(name="salt", recipe_id=sushiRecipe.id, amount=1, user_id=testUser.id,unit="pinch")
ingredient24 = Ingredient(name="cup", recipe_id=sushiRecipe.id, amount=1, user_id=testUser.id,unit="cup")
ingredient25 = Ingredient(name="Egg Yolk", recipe_id=sushiRecipe.id, amount=1, user_id=testUser.id,unit="single")
ingredient26 = Ingredient(name="Egg Whites", recipe_id=sushiRecipe.id, amount=2, user_id=testUser.id,unit="lightly beaten")
ingredient27 = Ingredient(name="Medium Shrimp", recipe_id=sushiRecipe.id, amount=1, user_id=testUser.id,unit="lb")
ingredient28 = Ingredient(name="black gram flour", recipe_id=indianRecipe.id, amount=8, user_id=testUser.id,unit="cup")
ingredient29 = Ingredient(name="black pepper", recipe_id=indianRecipe.id, amount=1, user_id=testUser.id,unit="tsp")
ingredient30 = Ingredient(name="cumin seeds", recipe_id=indianRecipe.id, amount=1, user_id=testUser.id,unit="tsp")
ingredient30 = Ingredient(name="salt", recipe_id=indianRecipe.id, amount=1, user_id=testUser.id,unit="tsp")
ingredient31 = Ingredient(name="oil", recipe_id=indianRecipe.id, amount=2, user_id=testUser.id,unit="tbsp")
ingredient32 = Ingredient(name="Spaghetti", recipe_id=italianRecipe.id, amount=1, user_id=testUser.id,unit="lb dried")
ingredient33 = Ingredient(name="Spaghetti Sauce", recipe_id=italianRecipe.id, amount=1, user_id=testUser.id,unit="16 oz jar")
ingredient34 = Ingredient(name="parmesan cheese", recipe_id=italianRecipe.id, amount=3, user_id=testUser.id,unit="tbsp")

session.add(ingredient1)
session.add(ingredient2)
session.add(ingredient3)
session.add(ingredient4)
session.add(ingredient5)
session.add(ingredient6)
session.add(ingredient7)
session.add(ingredient8)
session.add(ingredient9)
session.add(ingredient10)
session.add(ingredient11)
session.add(ingredient12)
session.add(ingredient13)
session.add(ingredient14)
session.add(ingredient15)
session.add(ingredient16)
session.add(ingredient17)
session.add(ingredient18)
session.add(ingredient19)
session.add(ingredient20)
session.add(ingredient21)
session.add(ingredient22)
session.add(ingredient23)
session.add(ingredient24)
session.add(ingredient25)
session.add(ingredient26)
session.add(ingredient27)
session.add(ingredient28)
session.add(ingredient29)
session.add(ingredient30)
session.add(ingredient31)
session.add(ingredient32)
session.add(ingredient33)
session.add(ingredient34)
session.commit()

